name: lab2
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
#  path: ^1.8.0
 dart_snmp:

dev_dependencies:
  pedantic: ^1.10.0
